### POST a new car
POST http://localhost:3000/api/cars HTTP/1.1
Content-Type: application/json

{
    "color": "red",
    "make": "Toyota",
    "model": "Corolla",
    "reg_number": "CA 12345"
}

###

### GET all cars
GET http://localhost:3000/api/cars HTTP/1.1

###

### PUT (update) a car
PUT http://localhost:3000/api/cars/CA%2012345 HTTP/1.1
Content-Type: application/json

{
    "color": "blue",
    "make": "Toyota",
    "model": "Corolla",
    "reg_number": "CA 12345"
}

###

### DELETE a car
DELETE http://localhost:3000/api/cars/CA%2012345 HTTP/1.1

###

### GET the count of Nissans from Malmesbury
GET http://localhost:3000/api/cars/nissans-from-ck HTTP/1.1

###
